# Generated by Django 3.2.23 on 2024-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellarapp', '0002_yourappnamelogrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logrecords',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='YourAppNameLogrecords',
        ),
    ]
