# Generated by Django 3.2.23 on 2024-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stellarapp', '0003_auto_20240226_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apilogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apilogs',
                'managed': False,
            },
        ),
    ]
